In [27]:
import pandas as pd
import requests
import time
import random
import re

In [28]:
from datetime import datetime, timedelta

# Current time in UTC
now = datetime.utcnow()

# Calculate the start time and end time
start_time = now.strftime("%Y-%m-%dT%H:%M:%SZ")  # Format as ISO 8601
end_time = (now + timedelta(weeks=1)).strftime("%Y-%m-%dT%H:%M:%SZ")  # 3 weeks later

# Construct the URL
print(start_time)
print(end_time)

2025-02-09T18:45:44Z
2025-02-16T18:45:44Z

In [ ]:
# Define the URL and parameters
url = "https://eu-offering-api.kambicdn.com/offering/v2018/ubnl/group/highlight.json"

# Headers to match the provided settings
headers = {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection": "keep-alive",
    "Origin": "https://www.unibet.nl",
    "Referer": "https://www.unibet.nl/",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "cross-site",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0"
}

# Additional query parameters
params = {
    "lang": "nl_NL",
    "market": "NL",
    "channel_id": "1",
    "client_id": "2",
    "depth": "0",
    "ncid": "1731338297307"
}

# Send GET request
response = requests.get(url, headers=headers, params=params)

# Check if the request was successful
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()
else:
    print(f"Request failed with status code: {response.status_code}")

In [30]:
# Extract desired fields
extracted_data = [
    {
        "name": group.get("name"),
        "sport": group.get("sport"),
        "pathTermId": group.get("pathTermId")
    }
    for group in data['groups']
]

# Convert to DataFrame
df = pd.DataFrame(extracted_data)

In [31]:
football_list = ['/football/costa_rica',
 '/football/world_cup_qualifying_-_south_america',
 '/football/uefa_womens_euro__w_',
 '/football/australia',
 '/football/scotland',
 '/football/romania',
 '/football/finland',
 '/football/argentina',
 '/football/south_africa',
 '/football/poland',
 '/football/northern_ireland',
 '/football/usa',
 '/football/colombia',
 '/football/paraguay',
 '/football/bahrain',
 '/football/israel',
 '/football/african_nations_cup',
 '/football/iraq',
 '/football/fifa_club_world_cup',
 '/football/conference_league',
 '/football/norway',
 '/football/russia',
 '/football/ukraine',
 '/football/england',
 '/football/denmark',
 '/football/sweden',
 '/football/spain',
 '/football/club_friendly_matches',
 '/football/champions_league__w_',
 '/football/iceland',
 '/football/champions_league',
 '/football/belgium',
 '/football/uefa_nations_league',
 '/football/france',
 '/football/turkey',
 '/football/europa_league',
 '/football/brazil',
 '/football/guatemala',
 '/football/mexico',
 '/football/greece',
 '/football/australia',
 '/football/italy',
 '/football/ethiopia',
 '/football/copa_libertadores',
 '/football/saudi_arabia',
 '/football/qatar'
 '/football/united_arab_emirates'
 '/football/egypt',
 '/football/germany',
 '/football/portugal',
 '/football/india',
 '/football/netherlands',
 '/football/cyprus',
 '/football/world_cup_qualifying_-_europe']

In [32]:
sports_list = list(set(list(set(df['pathTermId'])) + football_list))

In [ ]:
# sports_list = sports_list[:4]

In [8]:
# # Define the base URL
# base_url = "https://www.unibet.nl/sportsbook-feeds/views/filter/{}/all/matches"

# # Define headers and cookies
# headers = {
#     "Accept": "*/*",
#     "Accept-Encoding": "gzip, deflate, br, zstd",
#     "Accept-Language": "en-US,en;q=0.5",
#     "Connection": "keep-alive",
#     "Content-Type": "application/json",
#     "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0",
#     "Origin": "https://www.unibet.nl",
#     "Referer": "https://www.unibet.nl/betting/sports/filter"
# }

# cookies = {
#     "INGRESSCOOKIE_SPORTSBOOK_FEEDS": "d3eab806ac9dba5607cc45c4508ad6ad|e6f03e039bb9fba9ad84e4dd980ef8c9",
#     "clientId": "polopoly_desktop",
#     # Add other cookies as needed here...
# }

# # Initialize an empty list to collect event data
# all_events_data = []

# # Loop through each 'pathTermId' in the DataFrame
# for path_term_id in df['pathTermId']:
#     # Construct the URL with the pathTermId
#     url = base_url.format(path_term_id)

#     # Define the parameters
#     params = {
#         "includeParticipants": "true",
#         "useCombined": "true",
#         "ncid": "1731339326"
#     }

#     # Make the GET request
#     response = requests.get(url, headers=headers, params=params, cookies=cookies)

#     # Check the status code and parse the response
#     if response.status_code == 200:
#         data = response.json()
        
#         # Loop over events and gather the necessary information
#         try:
#             for event in data['layout']['sections'][1]['widgets'][0]['matches']['groups'][0]['events']:
#                 event_info = event.get('event', {})
#                 event_data = {
#                     'event_id': event_info.get('id'),
#                     'event_name': event_info.get('englishName'),
#                     'sport': event_info.get('sport')
#                 }
#                 all_events_data.append(event_data)
#         except:
#             for event in data['layout']['sections'][1]['widgets'][0]['matches']['events']:
#                 event_info = event.get('event', {})
#                 event_data = {
#                     'event_id': event_info.get('id'),
#                     'event_name': event_info.get('englishName'),
#                     'sport': event_info.get('sport')
#                 }
#                 all_events_data.append(event_data)
#     else:
#         print(f"Request failed for {path_term_id} with status code: {response.status_code}")

# # Convert the collected data to a DataFrame
# events_df = pd.DataFrame(all_events_data)

# # Display the DataFrame
# print(events_df)

In [9]:
# def process_strings(strings):
#     result = []
#     for s in strings:
#         slash_count = s.count('/')
#         if slash_count >= 3:
#             # Keep everything before the 3rd slash
#             result.append('/'.join(s.split('/')[:3]))
#         elif slash_count == 2:
#             # Keep the whole string
#             result.append(s)
#         else:
#             # Append nothing (empty string or skip)
#             result.append('')
#     return result

# # Example list
# strings = [
#  '/football/african_nations_cup',
#  '/football/belgium/jupiler_pro_league',
#  '/football/champions_league',
#  '/football/champions_league__w_',
#  '/football/conference_league',
#  '/football/copa_libertadores',
#  '/football/england/efl_cup',
#  '/football/england/fa_cup',
#  '/football/england/league_one',
#  '/football/england/league_two',
#  '/football/england/premier_league',
#  '/football/england/the_championship',
#  '/football/europa_league',
#  '/football/fifa_club_world_cup',
#  '/football/france/coupe_de_france',
#  '/football/france/ligue_1',
#  '/football/france/ligue_2/all/matches',
#  '/football/germany/2__bundesliga',
#  '/football/germany/bundesliga',
#  '/football/germany/dfb_pokal',
#  '/football/italy/coppa_italia',
#  '/football/italy/serie_a',
#  '/football/italy/serie_b',
#  '/football/netherlands/eerste_divisie',
#  '/football/netherlands/eredivisie',
#  '/football/netherlands/knvb_beker',
#  '/football/portugal/primeira_liga',
#  '/football/saudi_arabia/professional_league',
#  '/football/spain/copa_del_rey',
#  '/football/spain/la_liga',
#  '/football/spain/la_liga_2',
#  '/football/turkey/super_lig',
#  '/football/uefa_nations_league',
#  '/football/uefa_womens_euro__w_',
#  '/football/world_cup_qualifying_-_europe',
#  '/football/world_cup_qualifying_-_south_america',
# '/football/scotland/scottish_premiership',
# '/football/scotland/championship',
# '/football/scotland/league_one',
# '/football/scotland/league_two',
# '/football/australia/a-league',
# '/football/australia/a-league__w_',
# '/football/portugal/taca_da_liga',
# '/football/portugal/taca_de_portugal',
# '/football/portugal/taca_da_liga',
# '/football/belgium/challenger_pro_league',
# '/football/belgium/beker_van_belgie',
# '/football/belgium/jupiler_pro_league',
# '/football/brazil/baiano',
# '/football/brazil/carioca_a',
# '/football/brazil/catarinense',
# '/football/brazil/gaucho',
# '/football/brazil/goiano',
# '/football/brazil/maranhense',
# '/football/brazil/mineiro',
# '/football/brazil/paranaense',
# '/football/brazil/paulista_a1',
# '/football/brazil/pernambucano',
# '/football/brazil/potiguar',
# '/football/brazil/supercopa_do_brasil',
# '/football/club_friendly_matches',
# '/football/costa_rica/primera_division_costa_rica',
# '/football/egypt/premier_league',
# '/football/egypt/2nd_division',
# '/football/ethiopia/premier_league',
# '/football/greece/super_league',
# '/football/iceland/reykjavik_cup',
# '/football/india/super_league',
# '/football/iraq/premier_league',
# '/football/cyprus',
# 'football/india',
# 'football/kuwait',
# 'football/saudi_arabia',
# 'football/iceland',
# 'football/mali',
# 'football/mexico',
# 'football/wales',
# 'football/mali']

# # Process the list
# processed = process_strings(strings)
# list(set(processed))

In [ ]:
import requests
import pandas as pd

# Define the base URL
base_url = "https://www.unibet.nl/sportsbook-feeds/views/filter/{}/all/matches"

# Define headers and cookies
headers = {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection": "keep-alive",
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0",
    "Origin": "https://www.unibet.nl",
    "Referer": "https://www.unibet.nl/betting/sports/filter"
}

cookies = {
    "INGRESSCOOKIE_SPORTSBOOK_FEEDS": "d3eab806ac9dba5607cc45c4508ad6ad|e6f03e039bb9fba9ad84e4dd980ef8c9",
    "clientId": "polopoly_desktop",
    # Add other cookies as needed here...
}

# Initialize an empty list to collect event data
all_events_data = []


# Loop through each 'pathTermId' in the list
for path_term_id in sports_list:
    # Construct the URL with the pathTermId
    url = base_url.format(path_term_id)

    # Define the parameters
    params = {
        "includeParticipants": "true",
        "useCombined": "true",
        "ncid": "1731339326"
    }

    # Make the GET request
    response = requests.get(url, headers=headers, params=params, cookies=cookies)

    # Check the status code and parse the response
    if response.status_code == 200:
        try:
            data = response.json()
            
            # Check if 'layout' and the necessary sections exist
            if 'layout' in data and 'sections' in data['layout'] and len(data['layout']['sections']) > 1:
                sections = data['layout']['sections'][1]
                if 'widgets' in sections and len(sections['widgets']) > 0:
                    widgets = sections['widgets'][0]
                    if 'matches' in widgets:
                        matches = widgets['matches']
                        
                        # Check if 'groups' is present in matches
                        if 'groups' in matches and len(matches['groups']) > 0:
                            # Loop over all groups
                            for group in matches['groups']:
                                group_name = group.get('name', 'N/A')  # Get the group name, if available
                                if 'events' in group:
                                    # Loop over events and gather the necessary information
                                    for event in group['events']:
                                        event_info = event.get('event', {})
                                        event_data = {
                                            'event_id': event_info.get('id'),
                                            'event_name': event_info.get('englishName'),
                                            'start_time': event_info.get('start'),
                                            'sport': event_info.get('sport'),
                                            'country/sport': path_term_id.split('/')[-1],
                                            'group_name': group_name  # Include the group name here
                                        }
                                        all_events_data.append(event_data)
                                else:
                                    print(f"No 'events' key in group {group_name} for {path_term_id}")
                        elif 'events' in matches:
                            # Fallback: If 'groups' is not found, check if 'events' is directly under 'matches'
                            for event in matches['events']:
                                event_info = event.get('event', {})
                                event_data = {
                                    'event_id': event_info.get('id'),
                                    'event_name': event_info.get('englishName'),
                                    'start_time': event_info.get('start'),
                                    'sport': event_info.get('sport'),
                                    'group_name': 'N/A'  # No group in this case
                                }
                                all_events_data.append(event_data)
                        else:
                            print(f"No 'groups' or 'events' in matches for {path_term_id}")
                    else:
                        print(f"No 'matches' in widgets for {path_term_id}")
                else:
                    print(f"No 'widgets' in section for {path_term_id}")
            else:
                print(f"Invalid data structure for {path_term_id}")

        except Exception as e:
            print(f"Error processing {path_term_id}: {e}")
    else:
        print(f"Request failed for {path_term_id} with status code: {response.status_code}")

# Convert the collected data to a DataFrame
events_df = pd.DataFrame(all_events_data)

# Display the DataFrame
print(events_df)

     event_id                           event_name            start_time  \
0  1022723260                     Brest - Paris SG  2025-02-11T17:45:00Z
1  1022723285             Juventus - PSV Eindhoven  2025-02-11T20:00:00Z
2  1022723292  Sporting Lisbon - Borussia Dortmund  2025-02-11T20:00:00Z
3  1022723275        Manchester City - Real Madrid  2025-02-11T20:00:00Z
4  1022723293               Club Brugge - Atalanta  2025-02-12T17:45:00Z
5  1022723286                 Feyenoord - AC Milan  2025-02-12T20:00:00Z
6  1022723261                  AS Monaco - Benfica  2025-02-12T20:00:00Z
7  1022723277              Celtic - Bayern München  2025-02-12T20:00:00Z

      sport group_name
0  FOOTBALL        N/A
1  FOOTBALL        N/A
2  FOOTBALL        N/A
3  FOOTBALL        N/A
4  FOOTBALL        N/A
5  FOOTBALL        N/A
6  FOOTBALL        N/A
7  FOOTBALL        N/A

In [19]:
events_df[events_df['event_name'].str.contains('Manchester City')]

,event_id,event_name,start_time,sport,group_name,country/sport
41,1021042771,Manchester City - Newcastle United,2025-02-15T15:00:00Z,FOOTBALL,N/A,NaN
58,1021042759,Manchester City - Liverpool,2025-02-23T16:30:00Z,FOOTBALL,N/A,NaN
63,1021042771,Manchester City - Newcastle United,2025-02-15T15:00:00Z,FOOTBALL,Premier League,england
80,1021042759,Manchester City - Liverpool,2025-02-23T16:30:00Z,FOOTBALL,Premier League,england
100,1022776016,Manchester City (W) - Leicester City (W),2025-02-09T14:00:00Z,FOOTBALL,FA Cup (D),england
482,1022723275,Manchester City - Real Madrid,2025-02-11T20:00:00Z,FOOTBALL,N/A,NaN

In [11]:
events_df[events_df['event_name'].str.contains('PSV')]

,event_id,event_name,sport,country/sport,group_name
32,1021049436,NEC Nijmegen - PSV Eindhoven,FOOTBALL,NaN,N/A
48,1021049436,NEC Nijmegen - PSV Eindhoven,FOOTBALL,netherlands,Eredivisie
55,1021050019,Jong PSV Eindhoven - VVV Venlo,FOOTBALL,netherlands,Eerste Divisie
107,1022274702,PSV Eindhoven - Liverpool,FOOTBALL,NaN,N/A
126,1021050019,Jong PSV Eindhoven - VVV Venlo,FOOTBALL,NaN,N/A

## Loop through event IDs

In [20]:
import requests
import pandas as pd

# Assuming `events_df` is the DataFrame you've created from the previous example

# Get unique event IDs from the DataFrame
unique_event_ids = events_df['event_id'].unique()

# Define the base URL and parameters
base_url = 'https://eu-offering-api.kambicdn.com/offering/v2018/ubnl/betoffer/event/{event_id}.json'
params = {
    'lang': 'nl_NL',
    'market': 'NL',
    'client_id': '2',
    'channel_id': '1',
    'ncid': '1730829230569',
    'includeParticipants': 'true'
}
headers = {
    'accept': 'application/json, text/javascript, */*; q=0.01',
    'accept-encoding': 'gzip, deflate, br, zstd',
    'accept-language': 'en-US,en;q=0.9',
    'origin': 'https://www.unibet.nl',
    'priority': 'u=1, i',
    'referer': 'https://www.unibet.nl/',
    'sec-ch-ua': '"Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'
}

# Initialize an empty list to collect all rows
all_rows = []

# Loop through each unique event_id and make the request
for event_id in unique_event_ids:
    # Construct the URL with the current event_id
    url = base_url.format(event_id=event_id)
    
    # Make the request
    response = requests.get(url, headers=headers, params=params)

    # Check the response
    if response.status_code == 200:
        data = response.json()  # Parse the JSON response
        bet_offers = data.get('betOffers', [])  # Safely get the betOffers list
        
        for offer in bet_offers:
            for outcome in offer['outcomes']:
                row = {
                    'bet_offer_id': offer['id'],
                    'criterion_id': offer['criterion']['id'],
                    'criterion_label': offer['criterion']['label'],
                    'criterion_english_label': offer['criterion'].get('englishLabel', None),  # Safe access
                    'occurrence_type': offer['criterion'].get('occurrenceType', None),  # Safe access
                    'lifetime': offer['criterion'].get('lifetime', None),  # Safe access
                    'bet_offer_type_id': offer['betOfferType']['id'],
                    'bet_offer_type_name': offer['betOfferType']['name'],
                    'bet_offer_type_english_name': offer['betOfferType']['englishName'],
                    'event_id': offer['eventId'],
                    'outcome_id': outcome['id'],
                    'outcome_label': outcome['label'],
                    'outcome_english_label': outcome['englishLabel'],
                    'odds': outcome.get('odds', None),  # Safe access
                    'line': outcome.get('line', None),  # New field added
                    'participant': outcome.get('participant', None),  # New field added
                    'type': outcome['type'],
                    'changed_date': outcome['changedDate'],
                    'odds_fractional': outcome.get('oddsFractional', None),  # Safe access
                    'odds_american': outcome.get('oddsAmerican', None),  # Safe access
                    'status': outcome['status'],
                    'cash_out_status': outcome['cashOutStatus'],
                    'home_score': outcome.get('homeScore', None),  # Safe access
                    'away_score': outcome.get('awayScore', None)   # Safe access
                }
                all_rows.append(row)  # Append the row to the list

    else:
        print(f"Request for event_id {event_id} failed with status code:", response.status_code)

# After the loop, create the final DataFrame from all collected rows
final_df = pd.DataFrame(all_rows)

Request for event_id 1022805681 failed with status code: 404

In [24]:
final_df

,bet_offer_id,criterion_id,criterion_label,criterion_english_label,occurrence_type,lifetime,bet_offer_type_id,bet_offer_type_name,bet_offer_type_english_name,event_id,...,line,participant,type,changed_date,odds_fractional,odds_american,status,cash_out_status,home_score,away_score
0,2490701892,1002244276,Asian Totaal,Asian Total,GOALS,FULL_TIME,21,Asian Over/Under,Asian Over/Under,1021099806,...,2250.0,None,OT_OVER,2025-02-09T13:44:08Z,Evens,102,OPEN,DISABLED,None,None
1,2490701892,1002244276,Asian Totaal,Asian Total,GOALS,FULL_TIME,21,Asian Over/Under,Asian Over/Under,1021099806,...,2250.0,None,OT_UNDER,2025-02-09T13:44:08Z,4/6,-148,OPEN,DISABLED,None,None
2,2490701904,1001159926,Totaal Aantal Doelpunten,Total Goals,GOALS,FULL_TIME,6,Over/Onder,Over/Under,1021099806,...,3500.0,None,OT_OVER,2025-02-09T13:43:02Z,5/1,500,OPEN,ENABLED,None,None
3,2490701904,1001159926,Totaal Aantal Doelpunten,Total Goals,GOALS,FULL_TIME,6,Over/Onder,Over/Under,1021099806,...,3500.0,None,OT_UNDER,2025-02-09T13:43:02Z,1/9,-835,OPEN,ENABLED,None,None
4,2490701913,1002244276,Asian Totaal,Asian Total,GOALS,FULL_TIME,21,Asian Over/Under,Asian Over/Under,1021099806,...,2500.0,None,OT_OVER,2025-02-09T13:43:07Z,29/20,148,OPEN,DISABLED,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114979,2492682688,1002244276,Asian Totaal,Asian Total,GOALS,FULL_TIME,21,Asian Over/Under,Asian Over/Under,1022515071,...,3000.0,None,OT_UNDER,2025-02-09T11:19:05Z,12/25,-205,OPEN,DISABLED,None,None
114980,2492682689,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022515071,...,-1250.0,Al Riffa,OT_UNTYPED,2025-02-09T11:19:05Z,27/25,108,OPEN,DISABLED,None,None
114981,2492682689,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022515071,...,1250.0,Malkiya,OT_UNTYPED,2025-02-09T11:19:05Z,4/6,-148,OPEN,DISABLED,None,None
114982,2492682691,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022515071,...,-1500.0,Al Riffa,OT_UNTYPED,2025-02-09T11:19:05Z,7/5,140,OPEN,DISABLED,None,None
114983,2492682691,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022515071,...,1500.0,Malkiya,OT_UNTYPED,2025-02-09T11:19:05Z,13/25,-190,OPEN,DISABLED,None,None

In [26]:
final_df[final_df['event_id']==1022723275]

,bet_offer_id,criterion_id,criterion_label,criterion_english_label,occurrence_type,lifetime,bet_offer_type_id,bet_offer_type_name,bet_offer_type_english_name,event_id,...,line,participant,type,changed_date,odds_fractional,odds_american,status,cash_out_status,home_score,away_score
75448,2490101101,1001159858,Reguliere Speeltijd,Full Time,GOALS,FULL_TIME,2,Wedstrijd,Match,1022723275,...,NaN,Manchester City,OT_ONE,2025-02-09T13:08:45Z,11/8,138,OPEN,ENABLED,None,None
75449,2490101101,1001159858,Reguliere Speeltijd,Full Time,GOALS,FULL_TIME,2,Wedstrijd,Match,1022723275,...,NaN,None,OT_CROSS,2025-02-09T13:08:45Z,11/4,275,OPEN,ENABLED,None,None
75450,2490101101,1001159858,Reguliere Speeltijd,Full Time,GOALS,FULL_TIME,2,Wedstrijd,Match,1022723275,...,NaN,Real Madrid,OT_TWO,2025-02-09T13:08:45Z,39/20,195,OPEN,ENABLED,None,None
75451,2490102311,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022723275,...,-250.0,Manchester City,OT_UNTYPED,2025-02-09T13:08:46Z,Evens,100,OPEN,DISABLED,None,None
75452,2490102311,1002275572,Asian Handicap,Asian Handicap,GOALS,FULL_TIME,7,Asian Handicap,Asian Handicap,1022723275,...,250.0,Real Madrid,OT_UNTYPED,2025-02-09T13:08:46Z,10/13,-127,OPEN,DISABLED,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75905,2492703546,1001264082,Geeft Een Assist (Afgehandeld volgens Opta-geg...,To give an assist (Settled using Opta data),None,FULL_TIME,127,Player Occurrence Line,Player Occurrence Line,1022723275,...,1000.0,"Lewis, Rico",OT_YES,2025-02-09T13:08:46Z,13/2,650,OPEN,ENABLED,None,None
75906,2492703549,1003314795,Scoort of Geeft Een Assist (Afgehandeld volgen...,To score or give an assist (Settled using Opta...,None,None,127,Player Occurrence Line,Player Occurrence Line,1022723275,...,1000.0,"Camavinga, Eduardo",OT_YES,2025-02-09T13:08:46Z,24/5,480,OPEN,ENABLED,None,None
75907,2492703553,1003314795,Scoort of Geeft Een Assist (Afgehandeld volgen...,To score or give an assist (Settled using Opta...,None,None,127,Player Occurrence Line,Player Occurrence Line,1022723275,...,1000.0,"Lewis, Rico",OT_YES,2025-02-09T13:08:45Z,17/4,430,OPEN,ENABLED,None,None
75908,2492703557,1003314795,Scoort of Geeft Een Assist (Afgehandeld volgen...,To score or give an assist (Settled using Opta...,None,None,127,Player Occurrence Line,Player Occurrence Line,1022723275,...,1000.0,"Grealish, Jack",OT_YES,2025-02-09T13:08:45Z,41/20,205,OPEN,ENABLED,None,None
75909,2492703558,1001159997,Scoort van Buiten het Strafschopgebied,To score from outside the penalty box,None,FULL_TIME,127,Player Occurrence Line,Player Occurrence Line,1022723275,...,1000.0,"Grealish, Jack",OT_YES,2025-02-09T13:08:45Z,17/1,1700,OPEN,ENABLED,None,None

In [14]:
# Perform the left join on 'event_id' to get 'sport' and 'group_name' from events_df
final_df = final_df.merge(events_df[['event_id', 'event_name', 'sport', 'group_name']], on='event_id', how='left')

In [ ]:
# Function to reformat names from "Last, First" to "First Last"
def reformat_name(match_name):
    # Use regex to match "Last, First - Last, First" format
    formatted_names = re.sub(r"(\w+), (\w+)", r"\2 \1", match_name)
    formatted_names = formatted_names.replace(" - ", " vs ")
    return formatted_names

# Apply the function to the 'event_name' column
final_df['event_name'] = final_df['event_name'].apply(reformat_name)

# Define a function to swap and reformat the criterion_label for tennis
def swap_name_format(row):
    if row['sport'] == 'TENNIS':
        # Use regex to capture "Last name, First name" pattern and rearrange
        match = re.search(r"(\w+), (\w+) wint minstens één set", row['criterion_label'])
        if match:
            last_name, first_name = match.groups()
            # Reformat to "First name Last name Wint een Set"
            return f"{first_name} {last_name} Wint een Set"
    # Return the original criterion_label if conditions are not met
    return row['criterion_label']

# Apply the function to the criterion_label column
final_df['criterion_label'] = final_df.apply(swap_name_format, axis=1)

# Replace values in the 'type' column
final_df['type'] = final_df['type'].replace({'OT_ONE': '1', 'OT_TWO': '2'})

                                   criterion_label     sport
0  Totaal Aantal Doelpunten door Vitoria Guimarães  FOOTBALL
1  Totaal Aantal Doelpunten door Vitoria Guimarães  FOOTBALL
2  Totaal Aantal Doelpunten door Vitoria Guimarães  FOOTBALL
3  Totaal Aantal Doelpunten door Vitoria Guimarães  FOOTBALL
4                                     Asian Totaal  FOOTBALL

In [16]:
# Replace values in the 'type' column
final_df['type'] = final_df['type'].replace({'OT_ONE': '1', 'OT_TWO': '2'})

In [17]:
final_df[final_df['criterion_english_label'].str.contains('Draw')][[
       'bet_offer_type_id']]

        bet_offer_type_id
32                      2
33                      2
34                      2
35                      2
92                      2
...                   ...
143041                 18
143092                  2
143093                  2
143101                  2
143102                  2

[3051 rows x 1 columns]

In [18]:
final_output_name = 'unibetAllSports' + start_time + '.csv'
final_df.to_csv(final_output_name)

In [128]:
# final_df.to_csv('unibet_allSports_odds.csv')

In [32]:
import requests
from bs4 import BeautifulSoup

# URL of the webpage
url = "https://www.unibet.com/betting/sports/filter/football/all/matches"

# Add headers to mimic a browser
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Fetch the webpage
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find all 'a' tags with '/football/' in the href attribute
    football_links = [a['href'] for a in soup.find_all('a', href=True) if '/football/' in a['href']]
    
    # Print the links
    print("Links containing '/football/':")
    for link in football_links:
        print(link)
else:
    print(f"Failed to fetch the webpage. Status code: {response.status_code}")

Failed to fetch the webpage. Status code: 503